#!/usr/bin/env bash
export SERVER_PORT=3555
export POSTGRES_DB="games_database"
export POSTGRES_USER="yashbonde"
export POSTGRES_HOST="127.0.0.1"
export POSTGRES_PORT="5432"
export POSTGRES_PASSWORD=""
export DB_PATH="postgresql://{user}:{password}@{host}/{db_name}"
export MODEL_NAME="alphazero_value"
export ALPHAZERO_MODEL_NAME="bulletfuck"